import turtle
t=turtle.Turtle()
turtle.pensize(5)

signal = input("신호를 입력하세요(red, yellow, green)")

if signal == "red":
    t.penup()
    t.goto(0, 100)
    t.pendown()
    t.color("red")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    t.penup()
    t.goto(100, 100)
    t.pendown()
    t.color("yellow")
    t.circle(50)
    t.penup()
    t.goto(200, 100)
    t.pendown()
    t.color("green")
    t.circle(50)
elif signal == "yellow":
    t.penup()
    t.goto(0, 100)
    t.pendown()
    t.color("red")
    t.circle(50)
    t.penup()
    t.goto(100, 100)
    t.pendown()
    t.color("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    t.penup()
    t.goto(200, 100)
    t.pendown()
    t.color("green")
    t.circle(50)
elif signal == "green":
    t.penup()
    t.goto(0, 100)
    t.pendown()
    t.color("red")
    t.circle(50)
    t.penup()
    t.goto(100, 100)
    t.pendown()
    t.color("yellow")
    t.circle(50)
    t.penup()
    t.goto(200, 100)
    t.pendown()
    t.color("green")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
else:
    print("지원하지 않는 신호입니다.")

turtle.done()